# Generated by Django 5.2.8 on 2026-05-14 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CityArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='EcoArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zagolovok', models.CharField(max_length=255)),
                ('soderzhanie', models.TextField()),
                ('data_pub', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AirSensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm25_val', models.FloatField()),
                ('pm10_val', models.FloatField()),
                ('vremya', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AirForecastProject.cityarea')),
            ],
        ),
        migrations.CreateModel(
            name='ForecastData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horizon_hours', models.IntegerField()),
                ('predicted_pm25', models.FloatField()),
                ('vremya_prognoza', models.DateTimeField()),
                ('sensor_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AirForecastProject.airsensordata')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_interval', models.FloatField(default=1.0)),
                ('send_notifs', models.BooleanField(default=False)),
                ('chelovek', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('izbranniy_gorod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AirForecastProject.cityarea')),
            ],
        ),
        migrations.AddIndex(
            model_name='airsensordata',
            index=models.Index(fields=['vremya'], name='time_idx'),
        ),
        migrations.AddIndex(
            model_name='airsensordata',
            index=models.Index(fields=['city', 'vremya'], name='city_time_idx'),
        ),
    ]
