# Generated by Django 5.2.8 on 2026-05-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirForecastProject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecoarticle',
            name='url_article',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
