# Generated by Django 5.2.8 on 2026-05-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirForecastProject', '0002_ecoarticle_url_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='airsensordata',
            name='lat',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airsensordata',
            name='lon',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
