# Generated by Django 5.2.14 on 2026-05-14 22:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirForecastProject', '0003_airsensordata_lat_airsensordata_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airsensordata',
            name='vremya',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
