# Generated by Django 5.2.14 on 2026-05-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirForecastProject', '0004_alter_airsensordata_vremya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airsensordata',
            name='vremya',
            field=models.DateTimeField(),
        ),
    ]
