# Generated by Django 5.2.14 on 2026-05-15 00:01

import AirForecastProject.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirForecastProject', '0005_alter_airsensordata_vremya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airsensordata',
            name='vremya',
            field=models.DateTimeField(default=AirForecastProject.models.get_kyiv_time),
        ),
    ]
