# Generated by Django 5.2.14 on 2026-05-15 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirForecastProject', '0006_alter_airsensordata_vremya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airsensordata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cityarea',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ecoarticle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_pm25', models.FloatField()),
                ('predicted_pm10', models.FloatField()),
                ('prediction_hours', models.IntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_forecasts', to='AirForecastProject.cityarea')),
                ('lat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lat_forecasts', to='AirForecastProject.airsensordata')),
                ('lon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lon_forecasts', to='AirForecastProject.airsensordata')),
            ],
        ),
        migrations.DeleteModel(
            name='ForecastData',
        ),
    ]
