# Generated by Django 5.2.14 on 2026-05-15 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirForecastProject', '0007_alter_airsensordata_id_alter_cityarea_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='lon',
            field=models.FloatField(),
        ),
    ]
