# Generated by Django 5.2.14 on 2026-05-15 01:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirForecastProject', '0008_alter_forecast_lat_alter_forecast_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
