# Generated by Django 5.2.14 on 2026-05-15 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirForecastProject', '0009_forecast_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='location_name',
            field=models.CharField(default='Невідома локація', max_length=100),
        ),
    ]
