# Generated by Django 5.2.14 on 2026-05-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirForecastProject', '0011_modeltraininglog_systemstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemstate',
            name='current_epoch',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='systemstate',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='systemstate',
            name='total_epochs',
            field=models.IntegerField(default=0),
        ),
    ]
