# Generated by Django 5.2.14 on 2026-05-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirForecastProject', '0012_systemstate_current_epoch_systemstate_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_admin',
            field=models.BooleanField(default=False),
        ),
    ]
