# Generated by Django 5.2.14 on 2026-06-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirForecastProject', '0013_userprofile_user_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_notif_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
